### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by mukappalambda** [mukappalambda/go-examples#1]
- [ ] Survey how to update the go version of the existing project.
- [ ] Built-in testing best practices.
- [ ] Packages and modules template.
- [ ] Testing with Gin web framework (ref: https://gin-gonic.com/docs/testing/)

**Comment by mukappalambda** [comment]
As the first issue of this repository, its intention is rather broad and is not acceptable anymore nowadays.
